### Recuperar informacion del pokemon Ditto
GET http://localhost:1234/pokemon/ditto

### Pqra crear un Pokemon

POST http://localhost:1234/pokemon
Content-Type: application/json

{
    "name" : "ditto",
    "type" : "normal",
    "moves" : [
        "transform"
    ]
}